version: '3.9'
services:
  newman-tests:
    build:
      context: ./tests
      dockerfile: Dockerfile
    image: e2etest
    external_links:
      - odt-search
      - pdf-search
      - text-search
      - translation
    volumes:
      - ./tests:/app:rw
    networks:
      - techniki-komponentowe_test-net
networks:
  techniki-komponentowe_test-net:
    external: true