version: '3.9'
services:
  text-search:
    build:
      context: text-search
      dockerfile: Dockerfile
    ports:
      - "9001:80"
      - "9002:443"
    volumes:
      - ./samples:/app/files:ro
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      CHOKIDAR_USEPOLLING: "true"
      REACT_APP_BACKEND_URL: "${REACT_APP_BACKEND_URL:-http://backend:8080/}"
    volumes:
      - ./frontend:/app
      - /app/node_modules


