version: '3.9'
services:
  text-search:
    build:
      context: text-search
      dockerfile: Dockerfile
    ports:
      - "9001:80"
      - "9002:443"
    volumes:
      - "${SEARCH_DIRECTORY:-./samples}:/app/files:ro"
  odt-search:
    build:
      context: odt-search
      dockerfile: Dockerfile
    ports:
      - "9011:8182"
    volumes:
      - "${search_directory:-./samples}:/app/files:ro"
  pdf-search:
    build:
      context: pdf-search
      dockerfile: Dockerfile
    ports:
      - "9021:8183"
    volumes:
      - "${search_directory:-./samples}:/app/files:ro"
  audio-search:
    build:
      context: audio-search
      dockerfile: Dockerfile
    ports:
      - "9031:8184"
    volumes:
      - "${search_directory:-./samples}:/app/files:ro"
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - "${SEARCH_DIRECTORY:-./samples}:/app/files:ro"
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      CHOKIDAR_USEPOLLING: "true"
      REACT_APP_BACKEND_URL: "${REACT_APP_BACKEND_URL:-http://backend:8080/}"
    volumes:
      - ./frontend:/app
      - /app/node_modules
  test:
    build:
      context: ./odt-search/src/test/
      dockerfile: Dockerfile
    image: e2etest
    links:
      - odt-search
    volumes:
      - ./odt-search/src/test:/app:rw


