version: '3.9'
services:
  text-search:
    build:
      context: text-search
      dockerfile: Dockerfile
    ports:
      - "9001:80"
      - "9002:443"
    volumes:
      - "${SEARCH_DIRECTORY:-./samples}:/app/files:ro"
    networks:
      - test-net
      - internal
  odt-search:
    build:
      context: odt-search
      dockerfile: Dockerfile
    ports:
      - "9011:8182"
    volumes:
      - "${search_directory:-./samples}:/app/files:ro"
    networks:
      - test-net
      - internal
  pdf-search:
    build:
      context: pdf-search
      dockerfile: Dockerfile
    ports:
      - "9021:8183"
    volumes:
      - "${search_directory:-./samples}:/app/files:ro"
    networks:
      - test-net
      - internal
  audio-search:
    build:
      context: audio-search
      dockerfile: Dockerfile
    ports:
      - "9031:8184"
    volumes:
      - "${search_directory:-./samples}:/app/files:ro"
    networks:
      - internal
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - "${SEARCH_DIRECTORY:-./samples}:/app/files:ro"
    networks:
      - internal
  translation:
    build:
      context: translation
      dockerfile: Dockerfile
    networks:
      - internal
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - internal
    environment:
      CHOKIDAR_USEPOLLING: "true"
      REACT_APP_BACKEND_URL: "${REACT_APP_BACKEND_URL:-http://backend:8080/}"
    volumes:
      - ./frontend:/app
      - /app/node_modules

networks:
  test-net:
    driver: bridge
  internal:
    driver: bridge
