name: Smoke Tests
on: [push]
jobs:
  execute-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run all services
        run: docker-compose up -d --build frontend backend text-search
      - name: Wait for startup
        run: ./wait-for localhost:3000 -t 60
      - name: Run Cypress tests
        run: docker-compose --f docker-compose-e2e.yml up --build --exit-code-from cypress
