name: Smoke Tests
on: [push]
jobs:
  execute-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run all services
        run: docker-compose up -d --build
      - name: Wait for startup
        run: ./wait-for-all
      - name: Run Newman tests
        run: docker-compose --f docker-compose-newman.yml up --build --exit-code-from newman-tests
      - name: Run Cypress tests
        run: docker-compose --f docker-compose-cypress.yml up --build --exit-code-from cypress
